Add Animated Background similiar to Apple Music
playwora/wora pull request #30
Opened 2024-08-30 22:43 UTC by alvindimas05

Animated background trigerred when using is playing music.

![Screenshot 2024-08-31 at 05 41 43](https://github.com/user-attachments/assets/1f3e3fb5-db81-4ce2-9ebb-34bbab4933c2)

2024-09-06 10:44 UTC, hiaaryan commented
Great addition, would be great if this can be added as an option without affecting the core UI 🙌

2024-09-06 10:45 UTC, hiaaryan requested changes

2024-09-06 10:45 UTC, hiaaryan commented on package.json
> +    "sass": "^1.77.8",
This can't be done. Wora uses tailwind and adding a new preprocessor to the stack seems unnecessary.

2024-09-06 10:45 UTC, hiaaryan commented on renderer/components/main/player.tsx
> -          <div className="wora-border relative mt-2 h-full w-full rounded-2xl bg-white/70 backdrop-blur-xl dark:bg-black/70">
This would be forced. I feel maybe adding an option to enable/disable this feature would be great in settings alongside in the DB.

2025-03-24 11:08 UTC, nokids101 commented
This would be amazing if it was a toggle. Looks ✨stunning✨ Hopefully it could be implemented in the future 🤞🏼

2025-06-23 17:54 UTC, closed without merging